# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: required
filter_secrets: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/venv

# Ensure necessary system libraries are present
# addons:
#  apt:
#    sources:
#      - sourceline: ppa:fkrull/deadsnakes-python2.7
#    packages:
#      - libgmp-dev
#      - python2.7
#      - pv

before_install:
# Download and unpack the stack executable
- ./ci/setup-stack

stages:
  - test
  - name: build-doc-examples
    if: tag =~ ^docs OR branch = docs-master
  - name: build-docs
    if: tag =~ ^docs OR branch = docs-master

jobs:
  include:
    - stage: test
      script: ./ci/test
      addons:
        postgresql: "9.6"
      env: BEAM_RESOLVER=lts-10.3

    - stage: test
      script: ./ci/test
      addons:
        postgresql: "9.6"
      env: BEAM_RESOLVER=lts-11.2

    - stage: test
      script: ./ci/test
      addons:
        postgresql: "9.6"
      env: BEAM_RESOLVER=lts-12.0

    - stage: build-doc-examples
      addons:
        postgresql: "9.6"
      services:
        - postgresql

      before_install:
        - ./ci/setup-stack

      script: ./ci/build-docs-examples
      env: BEAM_DOC_BACKEND=beam-postgres

    - stage: build-doc-examples
      before_install:
        - ./ci/setup-stack
      script: ./ci/build-docs-examples
      env: BEAM_DOC_BACKEND=beam-sqlite

    - stage: build-doc-examples
      before_install:
        - ./ci/setup-stack
      services:
        - mysql
      script: ./ci/build-docs-examples
      env: BEAM_DOC_BACKEND=beam-mysql

    - stage: build-docs
      script: ./ci/build-docs
      env: BEAM_DOC_BACKENDS="beam-mysql beam-sqlite beam-postgres"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_DOCS_TOKEN
        local-dir: site
        on:
          branch: docs-master
