version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:latest
    steps:
      - checkout
      - run:
          name: Update nix
          command: nix-channel --update
      - run:
          name: Build
          command: stack --nix test --flag beam-core:werror --flag beam-sqlite:werror --flag beam-postgres:werror --flag beam-migrate:werror --resolver 12.0
